# Generated by Django 3.0.5 on 2020-05-11 14:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Mpesa', 'Mobile_money'), ('Insurance', 'Insurance'), ('Card', 'Card')], max_length=9)),
                ('payment_for', models.CharField(choices=[('Lab', 'Labaratory'), ('Con', 'Consultations'), ('Pharm', 'Pharmacy'), ('Ward', 'Admisions'), ('All', 'All payments')], max_length=15)),
                ('amount', models.IntegerField()),
                ('patient_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
            options={
                'db_table': 'payments',
                'managed': True,
            },
        ),
    ]
