# Generated by Django 3.0.5 on 2020-05-11 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_history', models.CharField(max_length=100)),
                ('admission', models.CharField(max_length=100)),
                ('test_types', models.CharField(choices=[('Lab', 'Labaratory'), ('cardio', 'cardiovascular'), ('skin', 'dermatology'), ('ENT', 'ENT'), ('gastro', 'gastrointerstinal'), ('blood', 'haematology'), ('brain', 'neurological'), ('gynae', 'gynaelogical'), ('visual', 'ocular'), ('joints', 'rheumatology'), ('heart', 'pulmonary'), ('imaging', 'radiology'), ('urine', 'urology')], max_length=20)),
                ('notes', models.CharField(max_length=500)),
                ('prescription', models.CharField(max_length=300)),
                ('patient_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
            options={
                'db_table': 'consultations',
                'managed': True,
            },
        ),
    ]
